# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 05:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180410_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default=datetime.datetime(2018, 4, 10, 5, 46, 22, 218636, tzinfo=utc), max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='wassup?', max_length=200),
        ),
    ]
