# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_watch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Care_givers',
            new_name='Care_giver',
        ),
    ]
