# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_watch', '0002_auto_20180413_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch_information',
            name='pub_date',
            field=models.DateTimeField(verbose_name='published'),
        ),
    ]
